services:
  - type: web
    name: basic-mcp
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: AUTH_TOKEN
        generateValue: true
      - key: PHONE_E164
        value: "919000000000"   # <-- change to your digits-only phone, e.g., 919876543210